//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Prj_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int id { get; set; }
        public string typeDeVehicule { get; set; }
        public string description_ { get; set; }
        public Nullable<int> idSociete { get; set; }
        public Nullable<int> idTrajet { get; set; }
    
        public virtual Societe Societe { get; set; }
        public virtual Trajet Trajet { get; set; }
    }
}
