//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Prj_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NavetteDB_Entities : DbContext
    {
        public NavetteDB_Entities()
            : base("name=NavetteDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonnement> Abonnements { get; set; }
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Affectation> Affectations { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Demande_Trajet> Demande_Trajet { get; set; }
        public virtual DbSet<Societe> Societes { get; set; }
        public virtual DbSet<Trajet> Trajets { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
    }
}
